import pylast

DB_USERNAME = ""
DB_PASSWORD = ""
DB_HOST = ""
DB_NAME = ""
SPOTIPY_CLIENT_ID = ""
SPOTIPY_CLIENT_SECRET = ""
LASTFM_API_KEY = ""
LASTFM_API_SECRET = ""
LASTFM_USERNAME = ""
LASTFM_PASSWORD = pylast.md5("")
