"""empty message

Revision ID: 389426c3d833
Revises: 7aad823fbfe8
Create Date: 2020-11-22 00:41:25.592234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389426c3d833'
down_revision = '7aad823fbfe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('error_updating', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('updating_playlist', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updating_playlist')
    op.drop_column('user', 'error_updating')
    # ### end Alembic commands ###
