"""empty message

Revision ID: 8c868851ddb5
Revises: 1d8898fd3f7e
Create Date: 2020-11-18 22:34:38.341023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c868851ddb5'
down_revision = '1d8898fd3f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('error_updating', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'error_updating')
    # ### end Alembic commands ###
