"""empty message

Revision ID: d4a9dcb22a24
Revises: 8c868851ddb5
Create Date: 2020-11-22 00:25:48.419015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4a9dcb22a24'
down_revision = '8c868851ddb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastfm_key')
    op.drop_column('user', 'lastfm_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastfm_name', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('user', sa.Column('lastfm_key', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
