"""empty message

Revision ID: dbfc5e244aab
Revises: 7eaf40266f43
Create Date: 2021-08-30 20:39:13.098339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbfc5e244aab'
down_revision = '7eaf40266f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('spotify_refresh_token', sa.String(length=256), nullable=True))
    op.drop_column('user', 'spotify_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('spotify_token', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('user', 'spotify_refresh_token')
    # ### end Alembic commands ###
